language: python
python:
- '3.6'
before_install:
- sudo apt-get update -qq
- pip install . --process-dependency-links
- pip install -r dev-requirements.txt
script:
- sheepdog-exporter -h
deploy:
  provider: pypi
  on:
    tags: true
  user: david4096
  password:
    secure: CgRDVjMPfbyWop6K0/Tv70HLMJoq4BdHKVMB/CBZm347gfiQw+Bx24aicJYFBW+sCdacKlFUfrux4EW0BUslf0dnkb0/3FmlFIAVC3cgi5NfcL/zCbvtlXDG31EMSqEWKGcIthEaPTu8tKKzpOWTtOLG9TlgpLUCUad/6nvT4hLyLg2Z+fsr1KvQ6MjaJTeBIK/QKTEi2Y7DYZaHg9mU5NXQmfBUHCIRQiv8wDG8MgOtICmx89xT7PSLLr1Ou1Vdm7Rh8TJqC/02Mlo3JTNf+GflbDnILJVPbq3dKfWu/iCo0xTaAtV0ZUShSDMnY6J2lF2CtfmKM6at1WqqhM+BGd8NGUAGSDOgRLH4FPoTqmUcuUIt+L2n2GjIIUakmMrexb8Uz1rXlXXqCEJAFckZYtzQiJumB9ZrIh9YXLuSNW/mbisdcCCz1FU0QhK1eV2SqIjhqE0uiAFiZuWphTSu0mnMGKQk/ko+fAzBaFHzQvAiohK7AC7Lg+8D0p/WuMjx2Ii1eXD6W4h0PSEvpib4O8W+nWXGM168+pzA29sXf/QkTik8lv7Ukqqmhy3JLybvhBytKp4ByUE7BouQVwN+uUqQj8dZQb/5YstV0R5lo08DPYSQMCZIPRq56K/+TvDi4YFk568JgZPglhNOkyIGMgAjI8rQbK8FrVST7TR4gaE=
